# Site settings
title: Dra. Vívian Ledur Machado
description: "Ortodontia de excelência"
baseurl: "" # the subpath of your site, e.g. /blog
url: http://mockery.asuscomm.com  # the name of your domain
logo_url: /img/logo_vivian.png
blog_url: blog

# Hero
hero: 
    hero_img: vivian_mesa2.jpg
    hero_title: Dra. Vívian Ledur Machado
    hero_description: Ortodontia de Excelência em Pelotas

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: (53) 3027-7966 / 98414-1552 (Whatsapp)
    phone2: (53) 3227-3750
    #emergency: 931 53 234
    email: contato@vivazespacodesaude.com.br
    address: <b>Vivaz Espaço de Saúde</b> <br> R. Anchieta, 3069 <br> Pelotas, RS
    address2: <b>Spazio Sorrir</b><br> R. Barão de Santa Tecla, 583<br> Pelotas, RS


# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: R. Anchieta, 3069, Pelotas
    address_details: img/logo_vivian_small.png #svg/min/logo.svg

# Social settings
facebook: https://www.facebook.com/vivianorto/
# twitter: http://twitter.com
instagram: https://www.instagram.com/vivianortodontista/
#youtube: http://youtube.com
#skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2018 Dra. Vívian Ledur Machado

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:



paginate: 5
paginate_path: blog/page:num
gems: [jekyll-paginate]
